### ISSUE TITLE
Issue with playing Wikipedia

### ISSUE THREAD

**Issue by JasonThomasData** [hatnote/l2w-native#1]
Hey,

Showed this to a colleague today.
It did not autoplay, since the 'English Wikipedia' checkbox returns 'Error'.
The website would not play at all.
However, the site works on my mobile phone.
My colleague's computer and mine are based within a corporate building, but there was no message to say the content was blocked or unavailable.

Thanks,

**Comment by mahmoud** [comment]
Hey Jason, thanks for the report! Yes, this is an issue we've seen with some corporations and institutions. If I recall, I think the problem is that the websocket library we're using makes it difficult to distinguish between recoverable and unrecoverable errors. Still, I think a general "Connecting/Still trying to connect" message would be good. 

@slaporte added one to http://rcmap.hatnote.com so we'll talk about making it happen for Listen to Wikipedia.

Also, for the record, this repo (l2w-native) is an android app i'm toying around with, versus https://github.com/hatnote/listen-to-wikipedia/ which is the web site. Thanks again!
